apiVersion: v1
kind: Pod
metadata:
  name: consul-master
  namespace: mall
  labels:
    app: consul-master
spec:
  containers:
    - name: consul-server
      image: consul
      imagePullPolicy: IfNotPresent
      command:
        - "/bin/sh"
        - "-c"
        - "consul agent -server -bootstrap-expect 1 -data-dir=/tmp/consul -node=n1 -bind=127.0.0.1 -client=0.0.0.0 -ui"
      ports:
        - containerPort: 8500
          protocol: TCP

---

apiVersion: v1
kind: Service
metadata:
  name: consul-server-service
  namespace: mall
spec:
  selector:
    app: consul-master
  type: NodePort
  ports:
    - port: 8500
      targetPort: 8500
      nodePort: 30850
      protocol: TCP

