apiVersion: apps/v1
kind: Deployment
metadata:
  name: diankuyun
  namespace: mall
  labels:
    deploy: diankuyun
spec:
  selector:
    matchLabels:
      app: diankuyun
  template:
    metadata:
      labels:
        app: diankuyun
    spec:
      containers:
        - name: diankuyun
          image: 50857500/hyperf-7.4:v1.0
          imagePullPolicy: IfNotPresent
          command:
            - "/bin/bash"
            - "-c"
            - "php /hyperf-skeleton/bin/hyperf.php start"
          ports:
            - containerPort: 9501
              protocol: TCP
          volumeMounts:
            - name: project
              mountPath: /hyperf-skeleton
      volumes:
        - name: project
          hostPath:
            path: /d/docker/www/diankuyun
            type: Directory

---

apiVersion: v1
kind: Service
metadata:
  name: diankuyun-service
  namespace: mall
spec:
  selector:
    app: diankuyun
  type: NodePort
  ports:
    - port: 9501
      targetPort: 9501
      nodePort: 31951
      protocol: TCP 