apiVersion: apps/v1
kind: Deployment
metadata:
  name: hyperf
  labels:
    deploy: hyperf
spec:
  selector:
    matchLabels:
      app: hyperf
  template:
    metadata:
      labels:
        app: hyperf
    spec:
      containers:
        - name: hyperf
          image: hyperf/hyperf:7.4-alpine-v3.12-swoole
          imagePullPolicy: IfNotPresent
          command:
            - "/bin/bash"
            - "-c"
            - "php /hyperf-skeleton/bin/hyperf.php start"
          ports:
            - containerPort: 9501
              protocol: TCP
          volumeMounts:
            - name: project
              mountPath: /hyperf-skeleton
      volumes:
        - name: project
          hostPath:
            path: /var/www/hyperf/
            type: Directory

---

apiVersion: v1
kind: Service
metadata:
  name: hyperf-svc
spec:
  selector:
    app: hyperf
  type: NodePort
  ports:
    - port: 9501
      targetPort: 9501
      nodePort: 30951
      protocol: TCP 