kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
containerdConfigPatches:
  - |
    [plugins."io.containerd.grpc.v1.cri".registry.mirrors."docker.io"]
      endpoint = ["https://docker.mirrors.ustc.edu.cn"]
nodes:
  - role: master
    kubeadmConfigPatches:
    - |
      kind: InitConfiguration
      nodeRegistration:
        kubeletExtraArgs:
          node-labels: "slave=master"
    extraPortMappings:
    - containerPort: 30060
      hostPort: 3306
      protocol: TCP
    - containerPort: 32080
      hostPort: 80
      protocol: TCP
    - containerPort: 32200
      hostPort: 9000
      protocol: TCP
    extraMounts:
    - hostPath: /var/data/
      containerPath: /var/www/