apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-conf
  namespace: mall
data:
  default.conf: |
    server {
      listen 80;
      root   /usr/share/nginx/html/admin/public/;
      server_name admin.mall.la;
      index  index.php

      client_max_body_size 20m;

      location / {
        try_files $uri $uri/ /index.php?$query_string;
      }

      location /storage/ {
        alias /usr/share/nginx/html/commonMedia/;
        autoindex on;
      }

      location ~ \.php$ {
        fastcgi_pass   10.106.72.201:9000;
        fastcgi_index  index.php;
        #这个www目录是php-fpm容器中的www目录
        fastcgi_param  SCRIPT_FILENAME  /var/www/html/admin/public/$fastcgi_script_name;
        include        fastcgi_params;
      }
    }

    server {
      listen 80;
      root   /usr/share/nginx/html/tenant/public/;
      server_name tenant.mall.la;
      index  index.php
      
      client_max_body_size 20m;

      location / {
        try_files $uri $uri/ /index.php?$query_string;
      }

      location /storage/ {
        alias /usr/share/nginx/html/commonMedia/;
        autoindex on;
      }

      location ~ \.php$ {
        fastcgi_pass   10.106.72.201:9000;
        fastcgi_index  index.php;
        #这个www目录是php-fpm容器中的www目录
        fastcgi_param  SCRIPT_FILENAME  /var/www/html/tenant/public/$fastcgi_script_name;
        include        fastcgi_params;
      }
    }

    server {
        listen 80;
        # 这个www目录是nginx容器中的www目录
        root   /usr/share/nginx/html/mall/public/;
        server_name mall.mall.la;

        client_max_body_size 20m;

        index index.php;
        location / {
          try_files $uri $uri/ /index.php?$query_string;
        }

        location /storage/ {
          alias /usr/share/nginx/html/commonMedia/;
          autoindex on;
        }

        location ~ \.php$ {
            fastcgi_pass   10.106.72.201:9000;
            fastcgi_index  index.php;
            #这个www目录是php-fpm容器中的www目录
            fastcgi_param  SCRIPT_FILENAME  /var/www/html/mall/public/$fastcgi_script_name;
            include        fastcgi_params;
        }
    }

    server {
        listen 80;
        # 这个www目录是nginx容器中的www目录
        root   /usr/share/nginx/html/public/guide/public/;
        server_name guide.mall.la;

        client_max_body_size 20m;

        index index.php;
        location / {
          try_files $uri $uri/ /index.php?$query_string;
        }

        location /storage/ {
          alias /usr/share/nginx/html/commonMedia/;
          autoindex on;
        }

        location ~ \.php$ {
            fastcgi_pass   10.106.72.201:9000;
            fastcgi_index  index.php;
            #这个www目录是php-fpm容器中的www目录
            fastcgi_param  SCRIPT_FILENAME  /var/www/html/guide/public/$fastcgi_script_name;
            include        fastcgi_params;
        }
    }
    