apiVersion: v1
kind: ConfigMap
metadata:
  name: redis-cluster-config
data:
  redis.conf: |
    appendonly yes
    cluster-enabled yes
    cluster-node-timeout 5000
    dir /var/lib/redis
    port 6379