apiVersion: v1
kind: Service
metadata:
  name: redis-service
  namespace: mall
spec:
  ports:
    - name: redis-port
      port: 6379
  clusterIP: None
  selector:
    app: redis-app
    appCluster:  redis-cluster

---

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: redis-cluster-app
  namespace: mall
spec:
  serviceName: redis-service
  selector:
    matchLabels:
      app: redis-app
  replicas: 6
  template:
    metadata:
      labels: 
        app: redis-app
        appCluster: redis-cluster
    spec:
      terminationGracePeriodSeconds: 10
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                labelSelector:
                  matchExpressions:
                    - key: app
                      operator: In
                      values: 
                        - redis-app
                topologyKey: kubernetes.io/hostname
      containers:
        - name: redis
          image: redis:latest
          imagePullPolicy: IfNotPresent
          ports:
            - name: redis
              containerPort: 6379
              protocol: "TCP"
          volumeMounts:
            - name: redis-conf
              mountPath: /etc/redis
            - name: redis-data
              mountPath: /var/lib/redis
      volumes:
        - name: redis-conf
          configMap:
            name: redis-cluster-config
        - name: redis-data
          hostPath: 
            path: /d/docker/redis/data
            type: DirectoryOrCreate