version: "3"
services:
  node1:
    image: consul
    container_name: node1
    command: agent -server -bootstrap-expect=3 -node=node1 -bind=0.0.0.0 -client=0.0.0.0
    volumes:
      - "/data/consul/node1/data:/consul/data"
      - "/data/consul/node1/config:/consul/config"
      - "/data/consul/node1/log:/consul/log"
    networks:
      - consul

  node2:
    image: consul
    container_name: node2
    command: agent -server -join=node1 -node=node2 -bind=0.0.0.0 -client=0.0.0.0
    volumes:
      - "/data/consul/node2/config:/consul/config"
      - "/data/consul/node2/data:/consul/data"
      - "/data/consul/node2/log:/consul/log"
    depends_on:
        - node1
    networks:
      - consul

  node3:
    image: consul
    container_name: node3
    command: agent -server -join=node1 -node=node3 -bind=0.0.0.0 -client=0.0.0.0
    volumes:
      - "/data/consul/node3/config:/consul/config"
      - "/data/consul/node3/data:/consul/data"
      - "/data/consul/node3/log:/consul/log"
    depends_on:
        - node1
    networks:
      - consul

  node4:
    image: consul
    container_name: node4
    command: agent -join=node1 -node=node4 -bind=0.0.0.0 -client=0.0.0.0 -ui
    volumes:
      - "/data/consul/node4/config:/consul/config"
      - "/data/consul/node4/data:/consul/data"
      - "/data/consul/node4/log:/consul/log"
    ports:
      - 8500:8500
    depends_on:
        - node2
        - node3
    networks:
      - consul

networks:
  consul: