apiVersion: v1
kind: Pod
metadata:
  name: redis
  labels:
    app: redis
spec:
  containers:
    - name: redis
      image: redis
      imagePullPolicy: Never
      ports:
        - containerPort: 6379
          protocol: TCP